#!/usr/bin/env python3
"""
Install (or remove) scheduled MAC/IP rotation via a systemd timer.

Runs one of the auto changers on a repeating schedule:

    sudo python3 tools/install_rotation.py -i wlan0
    sudo python3 tools/install_rotation.py -i wlan0 --ipv6 --every 30min
    sudo python3 tools/install_rotation.py -i wlan0 --tool 04_auto_ip_changer.py
    sudo python3 tools/install_rotation.py --uninstall

Scheduled runs use ``--no-save`` internally so the original configuration
saved by an earlier interactive run is never overwritten — ``restore`` always
reverts to the true original. Stop the rotation and restore with:

    sudo systemctl stop macip-rotate.timer
    sudo python3 tools/restore.py -i wlan0
"""

import argparse
import os
import sys
from pathlib import Path

import macip_lib
from macip_lib import MacipError

DEFAULT_DEST = "/etc/systemd/system"
DEFAULT_PREFIX = "macip-rotate"

TOOLS_DIR = Path(__file__).resolve().parent

SERVICE_TEMPLATE = """\
# Generated by MacIP install_rotation.py - do not edit by hand.
[Unit]
Description=MacIP - automatic MAC/IP rotation for {interface}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart="{python}" "{tool}" -i {interface} --no-save --times {times}{extra}
Nice=10
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
"""

TIMER_TEMPLATE = """\
# Generated by MacIP install_rotation.py - do not edit by hand.
[Unit]
Description=MacIP - rotate MAC/IP for {interface} every {every}

[Timer]
OnBootSec=1min
OnUnitActiveSec={every}
Unit={prefix}.service

[Install]
WantedBy=timers.target
"""


def get_arguments():
    parser = argparse.ArgumentParser(
        description="Schedule automatic MAC/IP rotation with a systemd timer"
    )
    parser.add_argument("-i", "--interface", required=True,
                        help="Network interface to rotate (e.g. wlan0, eth0)")
    parser.add_argument("--tool", default="06_auto_macip_changer.py",
                        help="Auto changer to run each cycle (default: 06_auto_macip_changer.py)")
    parser.add_argument("--times", type=int, default=1, metavar="N",
                        help="Rotations per timer fire (default: 1)")
    parser.add_argument("--ipv6", action="store_true",
                        help="Rotate random IPv6 addresses instead of IPv4")
    parser.add_argument("--network", default=None, metavar="CIDR",
                        help="IPv4 subnet for random addresses (passed to the changer)")
    parser.add_argument("--network6", default=None, metavar="CIDR",
                        help="IPv6 subnet for random addresses (passed to the changer)")
    parser.add_argument("--interval", type=float, default=None, metavar="SECONDS",
                        help="Seconds between changes inside a single run")
    parser.add_argument("--extra", default="", metavar="FLAGS",
                        help="Extra changer flags. Use '=' if the value starts "
                             "with '-', e.g. --extra=--times=3")
    parser.add_argument("--every", default="5min", metavar="SPEC",
                        help="Interval between rotations, systemd style (default: 5min)")
    parser.add_argument("--prefix", default=DEFAULT_PREFIX,
                        help="Unit name prefix (default: macip-rotate)")
    parser.add_argument("--dest", default=DEFAULT_DEST,
                        help=f"Directory for the unit files (default: {DEFAULT_DEST})")
    parser.add_argument("--uninstall", action="store_true",
                        help="Remove the scheduled rotation instead of installing it")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would happen without changing anything")
    return parser.parse_args()


def render_service_unit(python: str, tool: Path, interface: str,
                        times: int, extra: str) -> str:
    extra = f" {extra}" if extra else ""
    return SERVICE_TEMPLATE.format(
        python=python, tool=tool, interface=interface, times=times, extra=extra,
    )


def render_timer_unit(interface: str, every: str, prefix: str) -> str:
    return TIMER_TEMPLATE.format(interface=interface, every=every, prefix=prefix)


def _build_changer_flags(args) -> str:
    """Assemble the extra flags appended to the changer's ExecStart line."""
    flags = []
    if args.ipv6:
        flags.append("--ipv6")
    if args.network:
        flags += ["--network", args.network]
    if args.network6:
        flags += ["--network6", args.network6]
    if args.interval is not None:
        flags += ["--interval", str(args.interval)]
    parts = " ".join(flags)
    if args.extra:
        parts = f"{parts} {args.extra}".strip()
    return parts


def _systemctl(cmd, dry_run):
    if dry_run:
        macip_lib.log(f"[dry-run] would run: {' '.join(cmd)}")
        return
    try:
        result = macip_lib._run(cmd)
    except MacipError as exc:
        macip_lib.log(f"[-] Command failed: {exc}")
        return
    if result.returncode != 0:
        macip_lib.log(f"[-] Command failed ({result.returncode}): {' '.join(cmd)}")


def _install(args):
    tool_path = TOOLS_DIR / args.tool
    if not tool_path.is_file():
        raise MacipError(f"Tool '{args.tool}' not found in {TOOLS_DIR}.")
    if any(c in args.extra for c in ('"', "\n", "$", ";")):
        raise MacipError("--extra must not contain quotes, newlines, '$' or ';'.")
    if args.times < 1:
        raise MacipError("--times must be at least 1.")

    if os.name == "posix" and not macip_lib.interface_exists(args.interface):
        macip_lib.log(f"[-] Warning: interface '{args.interface}' does not seem to exist.")

    dest = Path(args.dest)
    service_file = dest / f"{args.prefix}.service"
    timer_file = dest / f"{args.prefix}.timer"

    extra = _build_changer_flags(args)
    service = render_service_unit(sys.executable, tool_path, args.interface,
                                  args.times, extra)
    timer = render_timer_unit(args.interface, args.every, args.prefix)

    macip_lib.log(f"[*] Writing {service_file}")
    macip_lib.log(f"[*] Writing {timer_file}")
    if not args.dry_run:
        dest.mkdir(parents=True, exist_ok=True)
        service_file.write_text(service)
        timer_file.write_text(timer)

    _systemctl(["systemctl", "daemon-reload"], args.dry_run)
    _systemctl(["systemctl", "enable", "--now", f"{args.prefix}.timer"], args.dry_run)

    macip_lib.log(
        f"[+] Scheduled rotation installed: {args.tool} on {args.interface} "
        f"every {args.every}."
    )
    macip_lib.log("    Check status: systemctl list-timers")
    macip_lib.log(f"    View logs: journalctl -u {args.prefix}.service -f")


def _uninstall(args):
    dest = Path(args.dest)
    _systemctl(["systemctl", "disable", "--now", f"{args.prefix}.timer"], args.dry_run)
    for name in (f"{args.prefix}.service", f"{args.prefix}.timer"):
        path = dest / name
        if path.exists():
            macip_lib.log(f"[*] Removing {path}")
            if not args.dry_run:
                path.unlink()
    _systemctl(["systemctl", "daemon-reload"], args.dry_run)
    macip_lib.log(f"[+] Scheduled rotation removed ({args.prefix}).")


def main():
    args = get_arguments()
    try:
        dest = Path(args.dest)
        if not args.dry_run and dest == Path(DEFAULT_DEST):
            macip_lib.require_root()
        if args.uninstall:
            _uninstall(args)
        else:
            _install(args)
    except MacipError as exc:
        macip_lib.log(f"[-] {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
